(() => {
  "use strict";
  const body=document.body,state=window.GameProgress?.getState()||{},screen8State=state.screen8||{},cipherReceived=Boolean(state.screen6?.cipherTableReceived);
  const inventoryLayer=document.querySelector("#inventory-layer"),inventoryList=document.querySelector("#inventory-list"),inventoryDetails=[...document.querySelectorAll(".inventory-detail")],chatPanel=document.querySelector("#robot-chat"),chatHistory=document.querySelector("#chat-history"),chatInput=document.querySelector("#chat-input"),questionnaire=document.querySelector("#time-order-form"),machineForm=document.querySelector("#time-machine-form"),leverBank=document.querySelector("#mini-lever-bank"),leverButtons=[...document.querySelectorAll("[data-mini-lever]")],sequenceSlots=[...document.querySelectorAll("#mini-sequence li")],leverField=document.querySelector("#lever-answer"),orderFeedback=document.querySelector("#order-feedback"),engineConfirm=document.querySelector("#engine-confirm"),lightbox=document.querySelector("#image-lightbox"),lightboxImage=document.querySelector("#lightbox-image"),lightboxTitle=document.querySelector("#lightbox-title");
  let lastFocus=null,awaitingCommand=false,sequence=[],activeLever=null,preparing=false,timeMachinePrepared=Boolean(screen8State.timeMachinePrepared);
  function appendMessage(role,text){const wrapper=document.createElement("div"),label=document.createElement("span"),bubble=document.createElement("p");wrapper.className=`chat-message chat-message-${role}`;label.textContent=role==="robot"?"ROBO":role==="system"?"SYSTEM":"YOU";bubble.textContent=text;wrapper.append(label,bubble);chatHistory.append(wrapper);chatHistory.scrollTop=chatHistory.scrollHeight;return wrapper}
  function openChat(){lastFocus=document.activeElement;chatPanel.hidden=false;document.querySelector(".robot-launch").hidden=true;requestAnimationFrame(()=>chatInput.focus())}function closeChat(){chatPanel.hidden=true;document.querySelector(".robot-launch").hidden=false;lastFocus?.focus()}
  document.querySelectorAll("[data-open-robot]").forEach(button=>button.addEventListener("click",openChat));document.querySelector("#robot-chat-close").addEventListener("click",closeChat);
  const normalize=value=>value.normalize("NFKC").replace(/[\s　。、！？!?「」『』]/g,"");
  const mentionsTimeMachine=value=>{const text=normalize(value);return text.includes("タイムマシン")||text.includes("たいむましん")};
  const isStartupCommand=value=>{const text=normalize(value);return ["起動","設置","セット","動かして","作動"].some(word=>text.includes(word))};
  function showQuestionnaire(){const instruction=appendMessage("robot","では以下の質問に答えてください");instruction.after(questionnaire);questionnaire.hidden=false;questionnaire.scrollIntoView({behavior:"smooth",block:"nearest"});document.querySelector("#machine-number").focus()}
  document.querySelector("#chat-form").addEventListener("submit",event=>{event.preventDefault();const value=chatInput.value.trim();if(!value)return;appendMessage("user",value);chatInput.value="";window.setTimeout(()=>{if(timeMachinePrepared){appendMessage("robot","タイムマシンの設置と起動は完了しています。");return}if(!questionnaire.hidden){if(value.includes("ヒント")||value.includes("ひんと"))appendMessage("robot","これまでに確認したタイムマシンの資料と、備品ケースを見直してみてください。");else appendMessage("robot","表示されている質問に回答してください。");return}if(awaitingCommand&&isStartupCommand(value)){awaitingCommand=false;showQuestionnaire();return}if(mentionsTimeMachine(value)){awaitingCommand=true;appendMessage("robot","タイムマシンをどうしてほしいのですか？");return}if(value.includes("ヒント")||value.includes("ひんと")){appendMessage("robot","これまでに確認したタイムマシンの資料と、備品ケースを見直してみてください。");return}appendMessage("robot","なんのことでしょう？")},300)});

  function renderSequence(){leverButtons.forEach((button,index)=>button.setAttribute("aria-pressed",String(index===activeLever)));sequenceSlots.forEach((slot,index)=>slot.textContent=sequence[index]===undefined?"—":leverButtons[sequence[index]].dataset.colorName);const full=sequence.length>=5;leverButtons.forEach(button=>button.disabled=full||timeMachinePrepared)}
  function resetLevers(){sequence=[];activeLever=null;leverField.classList.remove("is-correct","is-wrong");renderSequence()}
  leverBank.addEventListener("click",event=>{const button=event.target.closest("[data-mini-lever]");if(!button||sequence.length>=5||timeMachinePrepared)return;const index=Number(button.dataset.miniLever);if(index===activeLever)return;activeLever=index;sequence.push(index);renderSequence()});document.querySelector("#lever-reset").addEventListener("click",resetLevers);
  function markField(input,correct){const field=input.closest("[data-answer-field]");field.classList.toggle("is-correct",correct);field.classList.toggle("is-wrong",!correct);return correct}
  function completeTimeMachineOrder(){preparing=true;machineForm.querySelectorAll("input,button").forEach(control=>control.disabled=true);questionnaire.classList.add("is-complete");orderFeedback.textContent="回答を確認しました。タイムマシンの設置を開始します。";appendMessage("robot","了解しました。では、タイムマシンを起動してまいります。");window.setTimeout(()=>{timeMachinePrepared=true;window.GameProgress?.updateScreen8({timeMachinePrepared:true});appendMessage("robot","設置、起動完了です。");orderFeedback.textContent="タイムマシンの設置・起動が完了しました。エンジンを始動できます。"},2400)}
  machineForm.addEventListener("submit",event=>{event.preventDefault();if(preparing||timeMachinePrepared)return;const numberInput=document.querySelector("#machine-number"),locationInput=document.querySelector("#machine-location"),destinationInput=document.querySelector("#machine-destination"),timeInput=document.querySelector("#travel-time");const number=normalize(numberInput.value),location=normalize(locationInput.value),destination=normalize(destinationInput.value),travel=normalize(timeInput.value);const results=[markField(numberInput,/^(?:タイムマシン)?3(?:号)?$/.test(number)),markField(locationInput,location.includes("備品ケース")),markField(destinationInput,destination.includes("地球")),markField(timeInput,/^(?:1[5-9]|2[0-9]|30)分$/.test(travel))];const correctSequence=[0,4,1,4,0];const leverCorrect=correctSequence.every((value,index)=>sequence[index]===value)&&sequence.length===5;leverField.classList.toggle("is-correct",leverCorrect);leverField.classList.toggle("is-wrong",!leverCorrect);if(results.every(Boolean)&&leverCorrect){completeTimeMachineOrder();return}orderFeedback.textContent="赤く表示された回答を確認してください。"});

  document.querySelector("#engine-start").addEventListener("click",()=>{engineConfirm.hidden=false;body.classList.add("dialog-open");engineConfirm.querySelector("[data-engine-no]").focus()});function closeEngineConfirm(){engineConfirm.hidden=true;body.classList.remove("dialog-open");document.querySelector("#engine-start").focus()}document.querySelectorAll("[data-engine-no]").forEach(button=>button.addEventListener("click",closeEngineConfirm));document.querySelector("[data-engine-yes]").addEventListener("click",()=>{const ending=timeMachinePrepared?"true":"bad";window.GameProgress?.updateScreen8({engineStarted:true,ending});location.href=ending==="true"?"true-end.html":"bad-end.html"});

  function openInventory(){lastFocus=document.activeElement;inventoryLayer.hidden=false;body.classList.add("modal-open");inventoryLayer.querySelector("[data-close-inventory]").focus()}function closeInventory(){inventoryLayer.hidden=true;inventoryList.hidden=false;inventoryDetails.forEach(detail=>detail.hidden=true);body.classList.remove("modal-open");lastFocus?.focus()}document.querySelector("#inventory-open").addEventListener("click",openInventory);document.querySelectorAll("[data-close-inventory]").forEach(button=>button.addEventListener("click",closeInventory));document.querySelectorAll("[data-open-detail]").forEach(button=>button.addEventListener("click",()=>{inventoryList.hidden=true;const detail=document.querySelector(`#${button.dataset.openDetail}`);detail.hidden=false;detail.querySelector("[data-detail-back]").focus()}));document.querySelectorAll("[data-detail-back]").forEach(button=>button.addEventListener("click",()=>{const detail=button.closest(".inventory-detail");detail.hidden=true;inventoryList.hidden=false;document.querySelector(`[data-open-detail="${detail.id}"]`).focus()}));document.querySelector("#cipher-item").hidden=!cipherReceived;document.querySelector("#inventory-empty-slot").hidden=cipherReceived;document.querySelector("#inventory-count").textContent=cipherReceived?"3":"2";
  function openLightbox(button){lastFocus=button;lightboxImage.src=button.dataset.lightboxSrc;lightboxImage.alt=button.dataset.lightboxLabel;lightboxTitle.textContent=button.dataset.lightboxLabel;lightbox.hidden=false;body.classList.add("modal-open");lightbox.querySelector("[data-close-lightbox]").focus()}function closeLightbox(){lightbox.hidden=true;lightboxImage.src="";body.classList.remove("modal-open");lastFocus?.focus()}document.querySelectorAll("[data-lightbox-src]").forEach(button=>button.addEventListener("click",()=>openLightbox(button)));document.querySelectorAll("[data-close-lightbox]").forEach(button=>button.addEventListener("click",closeLightbox));
  document.addEventListener("keydown",event=>{if(event.key!=="Escape")return;if(!engineConfirm.hidden)closeEngineConfirm();else if(!lightbox.hidden)closeLightbox();else if(!inventoryLayer.hidden)closeInventory();else if(!chatPanel.hidden)closeChat()});
  renderSequence();if(timeMachinePrepared){appendMessage("robot","了解しました。では、タイムマシンを起動してまいります。");appendMessage("robot","設置、起動完了です。")}
})();
