(() => {
  "use strict";
  // 真エンドの二段階構成（離陸記録→物語→エンディング動画→結果表示）を順番に解放する。
  const launchVideo=document.querySelector("#true-launch-video"),launchTerminal=document.querySelector("#launch-terminal"),launchStatus=document.querySelector("#launch-status"),launchMessage=document.querySelector("#launch-message"),story=document.querySelector("#true-story"),endingVideo=document.querySelector("#ending-video"),endingTerminal=document.querySelector("#ending-terminal"),endingStatus=document.querySelector("#ending-status"),endingMessage=document.querySelector("#ending-message"),result=document.querySelector("#true-result");
  let storyRevealed=false,resultRevealed=false;
  function revealStory(){if(storyRevealed)return;storyRevealed=true;launchTerminal.classList.remove("is-playing");launchTerminal.classList.add("is-complete");launchStatus.textContent="PLAYBACK COMPLETE";launchMessage.textContent="離陸記録の再生が完了しました。";story.hidden=false;requestAnimationFrame(()=>{story.classList.add("is-revealed");story.scrollIntoView({behavior:"smooth",block:"start"})})}
  function revealResult(){if(resultRevealed)return;resultRevealed=true;endingTerminal.classList.remove("is-playing");endingTerminal.classList.add("is-complete");endingStatus.textContent="PLAYBACK COMPLETE";endingMessage.textContent="エンディングムービーの再生が完了しました。";result.hidden=false;requestAnimationFrame(()=>{result.classList.add("is-revealed");result.scrollIntoView({behavior:"smooth",block:"start"})})}
  const showLaunchError=()=>{launchTerminal.classList.remove("is-playing");launchStatus.textContent="VIDEO ERROR";launchMessage.textContent="YouTube動画を読み込めませんでした。通信環境を確認してページを再読み込みしてください。"};
  const showEndingError=()=>{endingTerminal.classList.remove("is-playing");endingStatus.textContent="VIDEO ERROR";endingMessage.textContent="YouTube動画を読み込めませんでした。通信環境を確認してページを再読み込みしてください。"};
  window.YouTubeEmbed.create(launchVideo,{onPlay:()=>{if(storyRevealed)return;launchTerminal.classList.add("is-playing");launchStatus.textContent="PLAYING";launchMessage.textContent="離陸記録を再生しています。"},onPause:()=>{if(storyRevealed)return;launchTerminal.classList.remove("is-playing");launchStatus.textContent="PAUSED";launchMessage.textContent="再生が一時停止しています。"},onEnded:revealStory,onError:showLaunchError}).catch(showLaunchError);
  window.YouTubeEmbed.create(endingVideo,{onPlay:()=>{if(resultRevealed)return;endingTerminal.classList.add("is-playing");endingStatus.textContent="PLAYING";endingMessage.textContent="エンディングムービーを再生しています。"},onPause:()=>{if(resultRevealed)return;endingTerminal.classList.remove("is-playing");endingStatus.textContent="PAUSED";endingMessage.textContent="再生が一時停止しています。"},onEnded:revealResult,onError:showEndingError}).catch(showEndingError);
})();
